
ACTION Act_EntP1050Disp:
	
	//Access Address
	p_tyC0005Main ACCESS ADR(tyCommon.tyMain);
	
	p_tyC0006Set ACCESS ADR(tyCommon.tySet);
	
	p_tyC0007Notif ACCESS ADR(tyCommon.tyNotif);
	
	p_tyC0008MsgBox ACCESS ADR(tyP1050LFSet.tyMsgBoxHide);
	
	p_tyC0009Info ACCESS ADR(tyCommon.tyInfo);
	
	p_tyC0011Loading ACCESS ADR(tyCommon.tyLoading);
	
	p_tyP1050LFSetLdrEdit ACCESS ADR(tyP1050LFSet.tyLdrEdit);
	
	p_tyP1050LFSetLdr ACCESS ADR(tyP1050LFSet.tyLdr);
	
END_ACTION
