
ACTION Act_ExitP1080: 

	tyP1080UsrMgmt.tyUsrMgmt.tyBtnNewUsr.bValue			:= FALSE;
	tyP1080UsrMgmt.tyUsrMgmt.tyBtnNewUsr.bRtCompl		:= FALSE;
	
	tyP1080UsrMgmt.tyUsrMgmt.tyBtnEditDetail.bValue		:= FALSE;
	tyP1080UsrMgmt.tyUsrMgmt.tyBtnEditDetail.bRtCompl	:= FALSE;
	
	tyP1080UsrMgmt.tyUsrMgmt.tyBtnDeleteUsr.bValue		:= FALSE;
	tyP1080UsrMgmt.tyUsrMgmt.tyBtnDeleteUsr.bRtCompl	:= FALSE;

	usiChgPage	:= 1;
	
END_ACTION
