
ACTION Act_EntP0950Disp:
	
	//Access Address
	p_tyC0005Main ACCESS ADR(tyCommon.tyMain);
	
	p_tyC0007Notif ACCESS ADR(tyCommon.tyNotif);
	
	p_tyC0008MsgBox ACCESS ADR(tyP0950Simu.tyMsgBoxHide);
	
	p_tyC0002FullMask ACCESS ADR (tyP0950Simu.tyFullMaskHide);
	
	p_tyC0009Info ACCESS ADR(tyCommon.tyInfo);
	
	p_tyP0950Simu ACCESS ADR(tyP0950Simu.tySimu);
		
	p_tyC0011Loading ACCESS ADR(tyCommon.tyLoading);

END_ACTION
